groups:
- name: SystemGuard's alert rules
  rules:
  - alert: InstanceDown
    annotations:
      description: Instance {{ $labels.instance }} is down for more than 5 minutes.
      runbook_url: https://example.com/runbook/instance-down
      summary: 'Instance Down '
    expr: up == 0
    for: 5m
    labels:
      severity: warning
  - alert: Cpu Usage
    annotations:
      description: CPU usage is above 60% for more than 2 minutes
      runbook_url: https://example.com/runbook/high-cpu-usage
      summary: Instance {{ $labels.instance }} high CPU usage.
    expr: avg by (instance) (cpu_usage_percentage{mode!="idle"}) > 95
    for: 1m
    labels:
      severity: warning
  - alert: Memory Usage
    annotations:
      description: Memory usage is above 80% for more than 2 minutes
      runbook_url: https://example.com/runbook/high-memory-usage
      summary: Instance {{ $labels.instance }} high memory usage.
    expr: avg by (instance) (memory_usage_percentage) > 90
    for: 1m
    labels:
      severity: warning
